### ISSUE TITLE
login cf return error behind firewall

### ISSUE THREAD

**Issue by Evy-Yang** [Evy-Yang/SAP#4]
first login cf return error behind firewall, and need me check proxy. When added proxy to env, then run cdw return error as below: 

Initializing Test Framework with HDI container: engagementcenter-hdi-container
Starting UI module: ./engagement-context/ui
#2.0#2018 11 20 15:10:12:801#+08:00#WARNING#/LoggingLibrary################PLAIN##Dynamic log level switching not available#
#2.0#2018 11 20 15:10:12:957#+08:00#INFO#/approuter################PLAIN##Application router version 2.7.1#
#2.0#2018 11 20 15:10:12:958#+08:00#INFO#/Configuration################PLAIN##Using empty destinations to run#
#2.0#2018 11 20 15:10:12:962#+08:00#WARNING#/Configuration################PLAIN##No authentication will be used when accessing backends. Scopes defined in routes will be ignored.#
#2.0#2018 11 20 15:10:12:970#+08:00#INFO#/approuter################PLAIN##Applicaiton router is listening on port: 4000#
Starting UI module: ./engagement-context/configui
#2.0#2018 11 20 15:10:13:080#+08:00#WARNING#/LoggingLibrary################PLAIN##Dynamic log level switching not available#
#2.0#2018 11 20 15:10:13:228#+08:00#INFO#/approuter################PLAIN##Application router version 2.7.1#
#2.0#2018 11 20 15:10:13:232#+08:00#WARNING#/Configuration################PLAIN##No authentication will be used when accessing backends. Scopes defined in routes will be ignored.#
#2.0#2018 11 20 15:10:13:237#+08:00#INFO#/approuter################PLAIN##Applicaiton router is listening on port: 4001#
Starting OData module: ./engagement-context/odata/server
error: Create instance manager error: GET - instances for all tenants - Error: tunneling socket could not be established, statusCode=403
/Users/i319878/git/scad-eh/node_modules/@sap/ec-deployer/deployer.js:90
      throw error;
      ^
 
Error: GET - instances for all tenants - Error: tunneling socket could not be established, statusCode=403
    at reportNetworkError (/Users/i319878/git/scad-eh/node_modules/@sap/instance-manager/lib/RestAdapter.js:138:12)
    at Request._callback (/Users/i319878/git/scad-eh/node_modules/@sap/instance-manager/lib/RestAdapter.js:22:14)
    at self.callback (/Users/i319878/git/scad-eh/node_modules/request/request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/Users/i319878/git/scad-eh/node_modules/request/request.js:878:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at ClientRequest.onConnect (/Users/i319878/git/scad-eh/node_modules/tunnel-agent/index.js:168:23)
    at Object.onceWrapper (events.js:319:30)
    at emitThree (events.js:136:13)
    at ClientRequest.emit (events.js:217:7)
    at Socket.socketOnData (_http_client.js:474:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cdw-workspace-manager@0.0.1 start: `node workspace-server.js -c components.json -hdi "engagementcenter-hdi-container"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cdw-workspace-manager@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Evy-Yang** [comment]
The final solution is uninstall the cf-cli, and re-install it. everything work well.
